set_property PACKAGE_PIN L16 [get_ports clk_in1]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1]
set_property PACKAGE_PIN G15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[23]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[24]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[4]}]
set_property MARK_DEBUG true [get_nets FrameTest_i/BoardInit_AXI_0/inst/rst_all_n]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[17]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[15]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[18]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[14]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[19]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[12]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[21]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[13]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[16]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[22]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[9]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/match0[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[8]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[10]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion2[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[11]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/harris_th[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion4[5]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/left[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/right[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion0[20]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion1[6]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[4]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[3]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/dilation0[7]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[0]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/erosion3[2]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/top[1]}]
set_property MARK_DEBUG true [get_nets {FrameTest_i/BoardInit_AXI_0/inst/bottom[6]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list FrameTest_i/clk_wiz_0/clk_out2]]
set_property port_width 9 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/top[0]} {FrameTest_i/BoardInit_AXI_0/inst/top[1]} {FrameTest_i/BoardInit_AXI_0/inst/top[2]} {FrameTest_i/BoardInit_AXI_0/inst/top[3]} {FrameTest_i/BoardInit_AXI_0/inst/top[4]} {FrameTest_i/BoardInit_AXI_0/inst/top[5]} {FrameTest_i/BoardInit_AXI_0/inst/top[6]} {FrameTest_i/BoardInit_AXI_0/inst/top[7]} {FrameTest_i/BoardInit_AXI_0/inst/top[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 25 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/erosion0[0]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[1]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[2]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[3]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[4]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[5]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[6]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[7]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[8]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[9]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[10]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[11]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[12]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[13]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[14]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[15]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[16]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[17]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[18]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[19]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[20]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[21]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[22]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[23]} {FrameTest_i/BoardInit_AXI_0/inst/erosion0[24]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/right[0]} {FrameTest_i/BoardInit_AXI_0/inst/right[1]} {FrameTest_i/BoardInit_AXI_0/inst/right[2]} {FrameTest_i/BoardInit_AXI_0/inst/right[3]} {FrameTest_i/BoardInit_AXI_0/inst/right[4]} {FrameTest_i/BoardInit_AXI_0/inst/right[5]} {FrameTest_i/BoardInit_AXI_0/inst/right[6]} {FrameTest_i/BoardInit_AXI_0/inst/right[7]} {FrameTest_i/BoardInit_AXI_0/inst/right[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/left[0]} {FrameTest_i/BoardInit_AXI_0/inst/left[1]} {FrameTest_i/BoardInit_AXI_0/inst/left[2]} {FrameTest_i/BoardInit_AXI_0/inst/left[3]} {FrameTest_i/BoardInit_AXI_0/inst/left[4]} {FrameTest_i/BoardInit_AXI_0/inst/left[5]} {FrameTest_i/BoardInit_AXI_0/inst/left[6]} {FrameTest_i/BoardInit_AXI_0/inst/left[7]} {FrameTest_i/BoardInit_AXI_0/inst/left[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/match0[0]} {FrameTest_i/BoardInit_AXI_0/inst/match0[1]} {FrameTest_i/BoardInit_AXI_0/inst/match0[2]} {FrameTest_i/BoardInit_AXI_0/inst/match0[3]} {FrameTest_i/BoardInit_AXI_0/inst/match0[4]} {FrameTest_i/BoardInit_AXI_0/inst/match0[5]} {FrameTest_i/BoardInit_AXI_0/inst/match0[6]} {FrameTest_i/BoardInit_AXI_0/inst/match0[7]} {FrameTest_i/BoardInit_AXI_0/inst/match0[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/harris_th[0]} {FrameTest_i/BoardInit_AXI_0/inst/harris_th[1]} {FrameTest_i/BoardInit_AXI_0/inst/harris_th[2]} {FrameTest_i/BoardInit_AXI_0/inst/harris_th[3]} {FrameTest_i/BoardInit_AXI_0/inst/harris_th[4]} {FrameTest_i/BoardInit_AXI_0/inst/harris_th[5]} {FrameTest_i/BoardInit_AXI_0/inst/harris_th[6]} {FrameTest_i/BoardInit_AXI_0/inst/harris_th[7]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/erosion2[0]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[1]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[2]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[3]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[4]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[5]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[6]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[7]} {FrameTest_i/BoardInit_AXI_0/inst/erosion2[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/erosion4[0]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[1]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[2]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[3]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[4]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[5]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[6]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[7]} {FrameTest_i/BoardInit_AXI_0/inst/erosion4[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/erosion3[0]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[1]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[2]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[3]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[4]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[5]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[6]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[7]} {FrameTest_i/BoardInit_AXI_0/inst/erosion3[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/erosion1[0]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[1]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[2]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[3]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[4]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[5]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[6]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[7]} {FrameTest_i/BoardInit_AXI_0/inst/erosion1[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/bottom[0]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[1]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[2]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[3]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[4]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[5]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[6]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[7]} {FrameTest_i/BoardInit_AXI_0/inst/bottom[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 9 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {FrameTest_i/BoardInit_AXI_0/inst/dilation0[0]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[1]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[2]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[3]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[4]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[5]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[6]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[7]} {FrameTest_i/BoardInit_AXI_0/inst/dilation0[8]}]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list FrameTest_i/BoardInit_AXI_0/inst/rst_all_n]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out2]
